name: Keepalive Render (cron)

on:
  schedule:
    - cron: "*/5 * * * *"  # ogni 10 minuti (UTC)
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: keepalive-render
  cancel-in-progress: false

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Ping Render URL (no-cache + token)
        env:
          KEEPALIVE_URL: ${{ secrets.KEEPALIVE_URL }}   # es: https://djshoprigenerato.onrender.com/_keepalive
          KEEPALIVE_TOKEN: ${{ secrets.KEEPALIVE_TOKEN }} # lo stesso impostato su Render
        run: |
          if [ -z "$KEEPALIVE_URL" ]; then
            echo "::error ::Missing secret KEEPALIVE_URL"; exit 1
          fi
          TS=$(date +%s)
          if [ -n "$KEEPALIVE_TOKEN" ]; then
            URL="${KEEPALIVE_URL}?t=${KEEPALIVE_TOKEN}&ts=${TS}"
          else
            URL="${KEEPALIVE_URL}?ts=${TS}"
          fi
          echo "Pinging: $URL"
          for i in 1 2 3; do
            http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
              -H "Cache-Control: no-cache" -H "Pragma: no-cache" \
              --max-time 20 "$URL") && ok=true || ok=false
            echo "Attempt #$i -> HTTP $http_code"
            if $ok && [ "$http_code" -ge 200 ] && [ "$http_code" -lt 500 ]; then
              exit 0
            fi
            sleep 5
          done
          echo "::warning ::Non-2xx/3xx response after retries"; exit 0
