
name: Keepalive Render (cron)

on:
  schedule:
    - cron: "*/5 * * * *"  # ogni 5 minuti (minimo)
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: keepalive-render
  cancel-in-progress: false

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Ping Render URL
        env:
          KEEPALIVE_URL: ${{ secrets.KEEPALIVE_URL }}
        run: |
          if [ -z "$KEEPALIVE_URL" ]; then
            echo "::error ::Missing secret KEEPALIVE_URL"; exit 1
          fi
          echo "Pinging: $KEEPALIVE_URL"
          for i in 1 2 3; do
            http_code=$(curl -sS -o /dev/null -w "%{http_code}" --max-time 20 "$KEEPALIVE_URL") && ok=true || ok=false
            echo "Attempt #$i -> HTTP $http_code"
            if $ok && [ "$http_code" -ge 200 ] && [ "$http_code" -lt 500 ]; then
              exit 0
            fi
            sleep 5
          done
          echo "::warning ::Non-2xx/3xx response after retries"; exit 0
